# Generated by Django 4.2.2 on 2023-07-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_product_age_remove_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory_name',
        ),
    ]
