# Generated by Django 4.2.2 on 2023-08-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
