# Generated by Django 4.2.2 on 2023-08-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_productcolor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
