# Generated by Django 4.2.2 on 2023-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0004_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='content',
            field=models.TextField(),
        ),
    ]
