# Generated by Django 4.2.2 on 2023-09-01 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0005_alter_usernotification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
