# Generated by Django 4.2.2 on 2023-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0006_alter_usernotification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
