# Generated by Django 4.2.2 on 2023-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_slug_orderitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='total_itemprice',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
