# Generated by Django 4.2.2 on 2023-08-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_total_price_orderitem_total_itemprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_itemprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
