# Generated by Django 4.2.2 on 2023-08-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_cart_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='payment',
            new_name='payment_method',
        ),
    ]
