# Generated by Django 4.2.2 on 2023-08-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_order_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.coupon'),
        ),
    ]
