# Generated by Django 4.2.2 on 2023-08-19 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0019_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Collected'), ('R', 'Recieved')], default='P', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Recieved')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='orderitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderitem'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
