# Generated by Django 4.2.2 on 2023-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_order_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_update',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
