# Generated by Django 4.2.2 on 2023-08-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_remove_order_last_update_orderitem_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returnpolicy',
            field=models.BooleanField(default=True),
        ),
    ]
