# Generated by Django 4.2.2 on 2023-08-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_orderitem_returnpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returnstatus',
            field=models.BooleanField(default=False),
        ),
    ]
