# Generated by Django 4.2.2 on 2023-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_orderitem_returnstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='total_price',
            field=models.PositiveIntegerField(default=300),
            preserve_default=False,
        ),
    ]
