# Generated by Django 4.2.2 on 2023-08-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_orderreturn_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
