# Generated by Django 4.2.2 on 2023-08-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_alter_wallethistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
