# Generated by Django 4.2.2 on 2023-08-25 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_wallethistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
