# Generated by Django 4.2.2 on 2023-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_orderreturn_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='task',
            field=models.TextField(),
        ),
    ]
