# Generated by Django 4.2.2 on 2023-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_alter_wallethistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveBigIntegerField(default=12345678),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('S', 'Shipped'), ('O', 'Out For Delivery'), ('D', 'Delivered'), ('C', 'Cancelled'), ('R', 'Returning')], default='P', max_length=1),
        ),
    ]
