# Generated by Django 4.2.2 on 2023-09-02 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_gcart_guestuser_gcartitem_gcart_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcart',
            name='guest_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.guestuser'),
        ),
    ]
