# Generated by Django 4.2.3 on 2023-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_address_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coin_discount',
            field=models.IntegerField(null=True),
        ),
    ]
